services:
  postgres:
    container_name: dream-container
    image: postgres
    hostname: ${DB_HOSTNAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB:            ${DB_NAME}
      POSTGRES_USER:          ${DB_USER}
      POSTGRES_PASSWORD:      ${DB_PASS}
      POSTGRES_ROOT_PASSWORD: ${DB_ROOT_PASS}
    restart: unless-stopped

  pgadmin:
    container_name: dream-pgadmin-container
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL:    ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
    restart: unless-stopped
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-data:
  pgadmin-data:

